apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecops-ingress
  annotations:
    # Réécrit l'URL pour enlever le préfixe (/service-a/foo -> /foo)
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
  - host: devsecops.local
    http:
      paths:
      # --- Route API Service A (Reste inchangée) ---
      - path: /service-a(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: service-a
            port:
              number: 8001
      
      # --- Route API Service B (Reste inchangée) ---
      - path: /service-b(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: service-b
            port:
              number: 8002

      # --- Route Principale pour le Frontend (NOUVEAU) ---
      # Avant c'était Keycloak, maintenant c'est ton site Web
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend  # Assure-toi que ton Service s'appelle bien "frontend"
            port:
              number: 80    # Le port du Service Frontend (pas du conteneur)
