apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      #imagePullSecrets:
      #- name: ghcr-secret
      containers:
      - name: service-a
<<<<<<< HEAD
        image: service-a:local
        #image: ghcr.io/chaben17/devsecops-lab/service_a:a94b4b750d19b1b080df75ea7a0560ce0bf8857c
=======
        image: devsecops-service-a:local
        #image: ghcr.io/chaben17/devsecops-lab/service_a:573f6361fd8447809ae7c12db174a2f746768f07
>>>>>>> 06bb25c64b39d7f6f1a741a187f5769ca8d11b72
        imagePullPolicy: Never  # <--- LE DÉTAIL CRUCIAL !
        #imagePullPolicy: Always
        ports:
        - containerPort: 8001
        # On s'occupera du volume partagé à l'étape suivante pour ne pas complexifier tout de suite
        volumeMounts:
        - name: shared-data
          mountPath: /data
      # 2. On définit quel est le disque réel (sur Minikube)
      volumes:
      - name: shared-data
        hostPath:
          path: /data
          type: Directory
