name: Build, Scan and Push to ECR
run-name: üê≥ Build, üõ°Ô∏è Scan & Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- SERVICE A ---
      
      - name: üê≥ Build Service A
        id: build-service-a
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          # On construit l'image mais ON NE PUSH PAS ENCORE
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:service-a-latest ./service_a

      - name: üõ°Ô∏è Trivy Scan Service A
        uses: aquasecurity/trivy-action@master
        with:
          # On scanne l'image qu'on vient de construire (disponible dans le cache Docker local)
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:service-a-latest
          format: 'table'
          exit-code: '0'          # Bloque le pipeline si vuln√©rabilit√© trouv√©e
          ignore-unfixed: true    # Ignore ce qu'on ne peut pas corriger
          vuln-type: 'os,library' # Scanne l'OS (Alpine/Debian) ET les libs (Pip/Maven)
          severity: 'CRITICAL,HIGH'


      # --- SERVICE B ---

      - name: üê≥ Build Service B
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:service-b-latest ./service_b

      - name: üõ°Ô∏è Trivy Scan Service B
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:service-b-latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: üöÄ Push Service A
        # Ne s'ex√©cute que si l'√©tape pr√©c√©dente (Scan) a r√©ussi
        if: success() 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:service-a-latest

      - name: üöÄ Push Service B
        if: success()
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:service-b-latest
